version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8
      - --skip-character-set-client-handshake
      - --general-log=true
      - --general-log-file=/tmp/mysql.log
      - --default-authentication-plugin=mysql_native_password
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
